name: daftar_pasien_klinik
description: A new Flutter project.
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  local_auth: ^2.1.0
  intl: ^0.18.1
  google_fonts: ^6.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google_icon.png
    - assets/apple_icon.png
    - assets/profile_placeholder.png